import type { ContentItem, HistoryEntry } from "./types";

export const INITIAL_ITEMS: ContentItem[] = [
  {
    id: 101,
    title: "Anotacoes no quadro",
    description: "Um registro rapido da aula antes que o assunto mudasse.",
    category: "Aula",
    type: "Foto",
    collection: "Rotina academica",
    privacy: "Publico",
    favorite: true,
    deleted: false,
    createdAt: "2026-08-18",
    updatedAt: "2026-08-26",
    image: "/jovi/mode-aula.webp",
  },
  {
    id: 102,
    title: "Encontro no campus",
    description: "Um momento espontaneo entre uma materia e outra.",
    category: "Campus",
    type: "Foto",
    collection: "Vida no campus",
    privacy: "Privado",
    favorite: false,
    deleted: false,
    createdAt: "2026-08-20",
    updatedAt: "2026-08-25",
    image: "/jovi/mode-campus.webp",
  },
  {
    id: 103,
    title: "Treino em movimento",
    description: "A acao registrada sem interromper o ritmo do treino.",
    category: "Treino",
    type: "Foto",
    collection: "Movimento",
    privacy: "Publico",
    favorite: true,
    deleted: false,
    createdAt: "2026-08-13",
    updatedAt: "2026-08-23",
    image: "/jovi/mode-treino.webp",
  },
  {
    id: 104,
    title: "Fim de dia em casa",
    description: "Uma memoria tranquila registrada em um ambiente com pouca luz.",
    category: "Casa",
    type: "Foto",
    collection: "Cotidiano",
    privacy: "Publico",
    favorite: false,
    deleted: false,
    createdAt: "2026-08-11",
    updatedAt: "2026-08-22",
    image: "/jovi/mode-casa.webp",
  },
  {
    id: 105,
    title: "Apresentacao do projeto",
    description: "Trecho em video da apresentacao da equipe Humanly.",
    category: "Aula",
    type: "Video",
    collection: "Rotina academica",
    privacy: "Privado",
    favorite: true,
    deleted: false,
    createdAt: "2026-08-09",
    updatedAt: "2026-08-21",
    image: "/jovi/mode-aula.webp",
  },
  {
    id: 106,
    title: "Roteiro de campo",
    description: "Documento de apoio para registrar os momentos da jornada de Lia.",
    category: "Campus",
    type: "Documento",
    collection: "Projeto JOVI",
    privacy: "Publico",
    favorite: false,
    deleted: false,
    createdAt: "2026-08-07",
    updatedAt: "2026-08-18",
    image: "/jovi/mode-campus.webp",
  },
];

export const INITIAL_HISTORY: HistoryEntry[] = [
  { id: 1, action: "Editado", item: "Anotacoes no quadro", date: "Hoje, 19:42" },
  { id: 2, action: "Adicionado", item: "Encontro no campus", date: "Ontem, 16:15" },
  { id: 3, action: "Favoritado", item: "Treino em movimento", date: "23 ago, 10:08" },
];
