import type { ContentItem, HistoryEntry } from "./types";

export const INITIAL_ITEMS: ContentItem[] = [
  {
    id: 101,
    title: "Design systems que escalam",
    description: "Principios para criar interfaces consistentes em equipes de produto.",
    category: "Design",
    type: "Artigo",
    collection: "Referencias",
    privacy: "Publico",
    favorite: true,
    deleted: false,
    createdAt: "2026-08-18",
    updatedAt: "2026-08-26",
    image: "https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 102,
    title: "React: composicao na pratica",
    description: "Uma aula direta sobre componentes reutilizaveis e fluxo de propriedades.",
    category: "Desenvolvimento",
    type: "Video",
    collection: "Estudos",
    privacy: "Privado",
    favorite: false,
    deleted: false,
    createdAt: "2026-08-20",
    updatedAt: "2026-08-25",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 103,
    title: "O futuro do trabalho criativo",
    description: "Conversa sobre tecnologia, repertorio e novas formas de colaborar.",
    category: "Carreira",
    type: "Podcast",
    collection: "Para ouvir",
    privacy: "Publico",
    favorite: true,
    deleted: false,
    createdAt: "2026-08-13",
    updatedAt: "2026-08-23",
    image: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 104,
    title: "Guia de acessibilidade digital",
    description: "Checklist essencial para produtos inclusivos e faceis de usar.",
    category: "Design",
    type: "Documento",
    collection: "Referencias",
    privacy: "Publico",
    favorite: false,
    deleted: false,
    createdAt: "2026-08-11",
    updatedAt: "2026-08-22",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 105,
    title: "IA aplicada a produtos digitais",
    description: "Casos praticos para automatizar tarefas sem perder o olhar humano.",
    category: "Tecnologia",
    type: "Video",
    collection: "Estudos",
    privacy: "Privado",
    favorite: true,
    deleted: false,
    createdAt: "2026-08-09",
    updatedAt: "2026-08-21",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: 106,
    title: "Pesquisa com usuarios",
    description: "Como planejar entrevistas e transformar sinais em decisoes.",
    category: "Pesquisa",
    type: "Artigo",
    collection: "Trabalho",
    privacy: "Publico",
    favorite: false,
    deleted: false,
    createdAt: "2026-08-07",
    updatedAt: "2026-08-18",
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=80",
  },
];

export const INITIAL_HISTORY: HistoryEntry[] = [
  { id: 1, action: "Editado", item: "Design systems que escalam", date: "Hoje, 19:42" },
  { id: 2, action: "Adicionado", item: "React: composicao na pratica", date: "Ontem, 16:15" },
  { id: 3, action: "Favoritado", item: "O futuro do trabalho criativo", date: "23 ago, 10:08" },
];

